spring:
  application:
    name: consul-producer
  cloud:
    consul:
      port: 8500
      host: localhost

server:
  port: 8081

management:
  endpoint:
    chaosmonkey:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
#        include: health,info,chaosmonkey

#  混沌测试的配置
chaos:
  monkey:
    enabled: true
    watcher:
      controller: true
      rest-controller: true
      repository: true
    assaults:
      exceptions-active: true
      level: 8
      kill-application-active: true
      latency-range-start: 1000
      latency-range-end: 10000

info:
  hello: good morning