
spring:
  application:
    name: spring-cloud-gateway
  cloud: 
    # 网关路由配置
    gateway:
      discovery:
        locator:
          enabled: true # gateway开启服务注册和发现的功能，根据serviceId来转发到具体的服务实例。默认为false,注意：serviceId默认大写
          lower-case-service-id: true  #配置serviceId小写
      routes:          
        - id: service_hello
          uri: lb://service-hello
          predicates:
            - Path=/aaa/** # 如果请求地址满足/aaa/**,则转发到 service-hello 服务
          filters:
           - StripPrefix=1 # 去除请求地址中的aaa
           # 限流配置
           - name: RequestRateLimiter
             args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5
                
#        - id: service1_v1
#          uri: http://localhost:8081/v1
#          predicates:
#            - Path=/test
#            - Weight=service1, 95 #权重配置
#
#        - id: service1_v2
#          uri: http://localhost:8081/v2
#          predicates:
#            - Path=/test
#            - Weight=service1, 5 #权重配置

    consul: # 服务发现的配置
      discovery:
        hostname: localhost
        port: 8500
server:
  port: 2200

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
