#spring:
#  application:
#    name: zuul
#server:
#  port: 2100
#
## 配置eureka server地址
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:2000/eureka/

#
#security:
#  oauth2:
#    resource:
#      logout:
#        url: http://localhost:2100/revoke-token
#      loadBalanced: true
#      userInfoUri: http://localhost:2100/me
#      jwt:
#        keyValue: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoZQfHaHQEzGuWBESlrcoM9DMiVM/fHEjLG7VK3COZ1xuM49P4pC+pNY3nm+wL/WM8QQdYNjPetzCiltLdW60rQa/+osW599SkmUSGF7rYXI9y4n1N4h0k9jLBdZ9n2/5miWWPDwrbsIGgLXp/NIsH4T2Gj6lUZuMj4cskIjU8P12S5TJEQ3N+PGYBY+G8zWzYB1dr3LssqATOqv1/XH+kPEesAtaaxJsfa/SWpaxDZnM5JGSjQ1/FEjyF2e0yAKbV/NqHnIqqnucr/StFBn/sGloEs1DAj8nIMtoiklqejqJvjCSdOC75f2N3iK72DgAVZkSNtfEdsVygHiOOtBtWQIDAQAB-----END\
#          \ PUBLIC KEY-----
#      id: zuul
#      serviceId: ${PREFIX:}zuul
#    client:
#      clientId: app_client_zuul
#      userAuthorizationUri: http://localhost:2100/oauth/authorize
#      accessTokenUri: http://localhost:2100/oauth/token
#      clientSecret: app_client_zuul_secret


# 网关路由配置
#zuul:
#  routes:
#    api-b:
#      path: /api-b/**
#      serviceId: service-feigin
#    api-a:
#      path: /api-a/**
#      serviceId: service-ribbon
