server:
  port: 2030
grpc:
  server:
    port: 9090
    address: 0.0.0.0
spring:
  application:
    name: grpc-demo-provider
  console:
    host: localhost
    port: 8500
# actuator management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# actuator info
info:
  app:
    encoding:UTF-8
    java.source:1.8
    java.traget:1.8
    name:grpc-demo-provider
