# 在dev的基础上加入了chaos monkey的配置

server:
  port: 2001

spring:
  application:
    name: service-hello
  cloud:
#####consul配置#####
    consul:
      host: localhost
      port: 8500
  sleuth:
    sampler:
      probability: 1
#####配置链路跟踪服务器地址#####  
  zipkin:
    base-url: http://localhost:4000
    enabled: true
    
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'